# Generated by Django 3.0.6 on 2020-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200601_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('contact', models.IntegerField(default=0)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
    ]
