# Generated by Django 3.0.6 on 2020-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='Lname',
        ),
        migrations.AddField(
            model_name='order',
            name='Fname',
            field=models.CharField(default='', max_length=90),
        ),
    ]
