# Generated by Django 3.0.6 on 2020-06-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200608_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AlterField(
            model_name='order',
            name='address1',
            field=models.CharField(max_length=300),
        ),
    ]
