# Generated by Django 3.0.6 on 2020-06-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200608_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Lname',
        ),
    ]
