# Generated by Django 3.0.6 on 2020-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default=0, max_length=20)),
                ('desc', models.TextField()),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
